<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-29T19:17:27 IST" name="Default suite" finished-at="2022-09-29T19:18:00 IST" duration-ms="33408">
    <groups>
    </groups>
    <test started-at="2022-09-29T19:17:27 IST" name="Default test" finished-at="2022-09-29T19:18:00 IST" duration-ms="33408">
      <class name="script.Test2">
        <test-method is-config="true" signature="initReport()[pri:0, instance:script.Test2@78691363]" started-at="2022-09-29T19:17:26 IST" name="initReport" finished-at="2022-09-29T19:17:27 IST" duration-ms="341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initReport -->
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.reflect.Method)[pri:0, instance:script.Test2@78691363]" started-at="2022-09-29T19:17:27 IST" name="openApp" finished-at="2022-09-29T19:17:45 IST" duration-ms="17849" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[config.properties]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void script.Test2.testB()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testB()[pri:2, instance:script.Test2@78691363]" started-at="2022-09-29T19:17:45 IST" name="testB" finished-at="2022-09-29T19:17:55 IST" duration-ms="10050" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CONTACT ME] but found [CONTACT US]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at script.Test2.testB(Test2.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.Test2@78691363]" started-at="2022-09-29T19:17:55 IST" name="closeApp" finished-at="2022-09-29T19:18:00 IST" duration-ms="5469" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=FAILURE method=Test2.testB()[pri:2, instance:script.Test2@78691363] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="publishReport()[pri:0, instance:script.Test2@78691363]" started-at="2022-09-29T19:18:00 IST" name="publishReport" finished-at="2022-09-29T19:18:01 IST" duration-ms="494" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- script.Test2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
